const SOUPS = {
  SOUPIFY: 'SOUP_LOAD',
  SOUPIFY_SUCCESS: 'SOUP_LOAD_SUCCESS',
  SOUPIFY_FAIL_OH_NO: 'SOUP_LOAD_FAIL'
}


const NOMS = {
  LOAD: 'NOMS_LOAD',
  LOAD_SUCCESS: 'NOMS_LOAD_SUCCESS',
  LOAD_FAIL: 'NOMS_LOAD_FAIL'
}

export { SOUPS, NOMS }